.github/workflows/signed-commits.yml

[Describe the high-level purpose of this pull request. What problem does it solve? What feature does it add? Link to any related issues or discussions.]
Please include a summary of the change and the issue it addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
-   [ ] Project Maintenance (updates to build scripts, …

Update signed-commits workflow to check only PR commits

---

.github/workflows/signed-commits.yml
SECURITY.md

Fixed the markdown to conform to the MarkdownLint checks.
Fixed formatting errors that were generating MarkdownLint errors and failures.
The changes pass the pre-commit-hook checks.
-   [X] My code follows the style guidelines of …

Fixed Lint Issues

---

docs/getting_started/faqs.mdx
docs/getting_started/introduction.mdx
docs/getting_started/quickstart.mdx
docs/open_source/community.mdx
docs/open_source/databases.mdx
docs/open_source/memory_types.mdx

Changes in this push regard the implementation of several areas of the docs website.
Changes include implementation of the FAQs section, implementation of several aspects of the Quick Start Guide, and resolving link issues in the Community page and Introduction Page.  Memory Tables have also been updated.
-   [ ] Project Maintenance (updates to build scripts, CI, etc., that do not affect the main …

Continued Updates to Build Docs Site

---

docs/examples/introduction.mdx
docs/getting_started/quickstart.mdx

Continued updates to docs site to prepare for product launch
Major updates to Examples section (inclusion of example .env file) and Installation guide section.
mint dev -port 3000 (tested on my own lab system)
-   [X] …

Examples and QuickStart Updates

---

src/server/app.py

Update the RESTful API
Remove the incomplete MCP API
Add the version to the REST API
-   [ ] Unit Test
-   [ ] Integration Test
-
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
-   [ ] Made sure Checks passed
-   [ ] Reviewed the code and verified the changes
[If applicable, add screenshots or GIFs that show the changes in …

Remove MCP and fix API version

---

.github/workflows/ruff.yaml

This pull request adds a GitHub Actions workflow to run Ruff, a fast Python linter, on pull requests. It aims to enforce Python coding style compliance (PEP8) automatically, improving code quality and consistency. This helps catch style issues early in the CI process.
Added a new workflow file `.github/workflows/ruff.yml` that triggers the Ruff linter on pull requests to the main branch. It uses the official `astral-sh/ruff-action@v3.5.1` GitHub Action to run Ruff checks on the specified source directory (`./src`). The action fails the workflow if style violations are found.
This change requires no additional dependencies aside from the GitHub Action itself. It improves developer feedback on code style during code review and pull request validation.
The workflow was tested by opening a …

Added Ruff Workflow Action

---

src/server/app.py

Current mcp path looks like this: `<server>/mcp/mcp`.
Changed to: `<server>/mcp`.
Removed path component `mcp` from http_app().
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Tested by starting server and calling a tool using OpenAI Agents SDK.
-   [ ] Unit Test
-   [ ] …

Remove extra MCP path component

---

docs/getting_started/introduction.mdx
docs/getting_started/quickstart.mdx
docs/openapi.json

Major edits to QuickStart Guide, API Name Changes, Adjusting card text for clarity
Changes surround clarity of API Names (to match industry standard), Adjusting text on a card for clarity, but major changes include instructions for how to install 3 separate methods (docker compose, pip, and source) as well as HelloWorld examples for our 3 separate APIs (REST, MCP, PythonSDK).
-   [ ] …

Major edits to QuickStart Guide, API Name Changes, Adjusting card text for clarity

---

src/memmachine/profile_memory/storage/asyncpg_profile.py

Whereas citations are not really useful in most cases in which one would want a profile, empirical testing in an integrated system (including both the profile and episodic memories) on the LoCoMo benchmark demonstrate reduced LLM judge scores, and the use case for citations can overlap with the use case for episodic memory, it makes sense to disable returning profile citations by default.
Add a parameter to the profile's `semantic_search()` to disable returning citations by default.
This breaks any agents that expect citations to be returned by default.
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing …

Disable profile citations by default

---

maintainers/pull-requests.md

Updated the steps for a reviewer to clarify the early-stage requirements and demonstrate how to add a remote contributor's GitHub repository as a remote repository using both HTTPS and SSH.
As above
-   [x] Documentation update
-   [x] Project Maintenance (updates to build scripts, CI, etc., that do not affect the main project)
I tested the updates myself with a …

Updated pull-requests.md. Added HTTPS and SSH examples when cloning the contributors fork.

---

evaluation/locomo/episodic_memory/README.md
evaluation/locomo/episodic_memory/locomo_delete.py
evaluation/locomo/episodic_profile_agent/README.md
evaluation/locomo/episodic_profile_agent/locomo_delete.py

Make it easier to delete LoCoMo evaluation data.
Add scripts to delete data from episodic memory.
Document relevant scripts in READMEs.
-   [x] Documentation update
-   [x] Project Maintenance (updates to build scripts, CI, etc., that do not affect the main project)
Only tested the episodic memory deletion script. The script for the benchmark using agent is the …

Add instructions to delete LoCoMo evaluation data

---

docs/examples/introduction.mdx
docs/getting_started/quickstart.mdx
docs/open_source/community.mdx

This edit fixes some issues brought out during feedback reviews in the past day.
Fixes included in this PR are to links (mainly on the community page, but also on the examples/introduction page).   It also holds adjustments to our Quickstart Guide based on feedback.
-   [ ] Security …

Quick Documentation Fixes

---

docs/getting_started/quickstart.mdx

The `memmachine-compose.sh` script (new name) needed to be reflected in our Method 1 of the Quickstart Guide for Installation.  This PR also temporarily removes Methods 2 and 3, which will need to be enhanced based on the new releases (when they come out). 
Made a copy of the existing quickstart.mdx file, then removed all accordions (replacing with steps) and removed methods 2 and 3.  Updated Method 1 to reflect the new script name, as well as added an additional step, which provides information on the other commands this script can do (such as stop, restart, etc), as knowledge of such commands is vital for users to be able to remove the script, among other options.
Please describe the tests that you ran to verify your changes. Provide …

Changes to QuickStart Guide for memmachine-compose.sh behavior and name

---

src/memmachine/common/reranker/cross_encoder_reranker.py

Fix memory leak when using Sentence Transformers CrossEncoder-based rerankers. 
Creating multiple CrossEncoder instances causes memory leak on system tested.
To solve this, we only create a single CrossEncoder instance for each different local model.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Security (improves security without …

Fix CrossEncoderReranker memory leak

---

.github/workflows/docker-image.yml

[Describe the high-level purpose of this pull request. What problem does it solve? What feature does it add? Link to any related issues or discussions.]
Please include a summary of the change and the issue it addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.
-   [ ] Project Maintenance (updates to build scripts, …

Optimized Docker Build Workflow

---

src/memmachine/server/app.py

Server API calls nonexistent methods.
Replaced calls to nonexistent EpisodicMemoryManager methods with existing methods.
Sorted imports and formatted.
-   [x] Bug fix (non-breaking change which fixes an issue)
Not tested.
-   [ ] Unit Test
-   [ …

Fix calls to nonexistent EpisodicMemoryManager methods in server app.py

---

src/memmachine/common/embedder/embedder.py
src/memmachine/common/embedder/openai_embedder.py
src/memmachine/common/language_model/language_model.py
src/memmachine/common/language_model/openai_language_model.py
src/memmachine/episodic_memory/declarative_memory/declarative_memory.py
src/memmachine/profile_memory/profile_memory.py
tests/memmachine/episodic_memory/short_term_memory/test_session_memory.py

Handle LLM model error.
In this change, when LLM model call fails, the vendor specific exception is caught and translated to python common exception. The model user should catch the exception and handle it properly.
Fixes #109 
Fixes #89 
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Security (improves security without changing …

Handle LLM error. issue #109 #89

---

src/memmachine/profile_memory/profile_memory.py

Some change in #123 broke the profile memory.
Fix variable naming.
Not tested. Checks pass now.

Fix profile memory variable naming

---

docs/docs.json
docs/getting_started/install_guide.mdx
docs/getting_started/introduction.mdx
docs/getting_started/quickstart.mdx

Pip and source installations required a rewrite and better organization.  We separated it from the QuickStart guide, and now they will reside in this "Installation Guide".
Creation of a new install_guide.mdx file and reorganization of instructions for installation to make a possibly complex situation simpler to understand.  Utilized Accordions when feasible to reduce overall screen scroll and also simply user experience.  Includes example configuration files and logic for when to leave comments in (and when to remove them) based on GPU vs. CPU utilization.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Adding Installation Guide for pip and source installations.

---

docs/api_reference/intro.mdx
docs/openapi.json

Adjusting API Reference information to reflect new REST API call as well as edits to adjust for 0.1.2 release.
Added new /health REST API, ensured nomenclature within new openapi.json file reflects current styles and uses, added in missing MCP Server description which was removed in a previous release.
[If applicable, add screenshots or GIFs that show the changes in action. This is especially helpful for API responses. Otherwise, delete this section or type …

0.1.2 release updates to API Reference Section

---

pyproject.toml
uv.lock

Make it easier to set up development environment.
Add pytest and pytest-asyncio to dev dependency group.
Changes are automatically generated by running `uv add --dev pytest pytest-asyncio`.
Not tested.

Add pytest packages to dev dependencies

---

src/memmachine/profile_memory/profile_memory.py

Bug fix in profile memory
The LLM model API return a tuple with response and tool call arguments. But in profile memory, the return value is used as a string, which results in error.
#171 
Add a message to profile memory, it should work.
[If applicable, add screenshots or GIFs that show the changes in action. This is especially helpful for API responses. Otherwise, delete this section or type …

Fix profile memory model usage error

---

src/memmachine/profile_memory/profile_memory.py

Fix an error in profile memory
When consolidating profile memory, a wrong variable used in the code. This results in program error.
#161 
[If applicable, add screenshots or GIFs that show the changes in action. This is especially helpful for API responses. Otherwise, delete this section or type "N/A".]
[Add any other relevant information here, such as potential side effects, future …

Fix an error in profile memory

---

docs/api_reference/python/episodic_memory.mdx
docs/api_reference/python/episodic_memory_manager.mdx
docs/api_reference/python/memory_types.mdx
docs/api_reference/python/profile_memory.mdx
docs/getting_started/install_guide.mdx
docs/openapi.json

The 0.1.3 release introduced new APIs and config.yaml sample files.  Documentation needs to be updated to reflect these new changes.
Updated the RESTful and MCP Server APIs to include new options.  Updated all 4 Python SDK areas to reflect current options, and updated the Install Guide to reflect new GPU and CPU specific config.yml files.   File examples are located in the Install Guide, and links were created for curl commands based on new file name nomenclature.
**Test Results:** NA
N/A
None.

Updating Documentation for 0.1.3 Release

---

src/memmachine/profile_memory/profile_memory.py

Wrong variable is still used in multiple places.
Same as #174, #175

Fix wrong variable used

---

.github/workflows/pytest.yml
.github/workflows/ruff.yaml
.github/workflows/sbom.yml
src/memmachine/__init__.py
tests/memmachine/common/reranker/test_bm25_reranker.py

Add unit test run to github CI for all supported versions of python.
This ensures all PRs pass existing unit tests.
Additionally adds the setup of nltk datasets to the bm25 reranker unit tests.

Add pytest CI testing

---

.gitignore

Have `.gitignore` include popular IDE configs to avoid accidentally including or committing them.

Add Gitignore entries for popular IDEs

---

CONTRIBUTING-CORE.md
maintainers/running-unit-tests.md

It is confusing to have references to two different package/dependency/environment management systems in the docs.
We are using uv for dependency management. Compatibility with other tools is unknown.
We also have too many docs that repeat the same instructions but slightly differently.
Remove references to poetry.
For project setup, reference CONTRIBUTING-CORE.md instead of providing a new set of instructions.
Not tested.

Remove references to Poetry

---

evaluation/locomo/episodic_agent/locomo_delete.py
evaluation/locomo/episodic_agent/locomo_ingest.py
evaluation/locomo/episodic_memory/locomo_delete.py
evaluation/locomo/episodic_memory/locomo_ingest.py
evaluation/locomo/episodic_memory/locomo_search.py

EpisodicMemoryManager.get_episodic_memory_instance() no longer takes a config path.
Remove unnecessary config override.
Delete lines specifying a config path for get_episodic_memory_instance.
Tested one ingestion script via `python locomo_ingest.py --data-path ../locomo10.json` from evaluation/locomo/episodic_memory. All others should work because the scripts call the API in the same way.

Update episodic memory API usage in evaluation scripts

---

examples/README.md
examples/financial_analyst/financial_server.py
examples/health_assistant/health_server.py
sample_configs/episodic_memory_config.cpu.sample
sample_configs/episodic_memory_config.gpu.sample

The REST API calls in the examples for the health assistant and financial analyst were out of date. Also the sample config uses the writing assistant prompt for some reason. Also removed the curl request from the examples README since it tests for the backend app.py functionality. 
Updated the endpoints and fixed the sample config. 
Local Test
N/A
None

Fix API calls in the examples and also change the sample config to use the default profile_prompt.py

---

src/memmachine/common/data_types.py
src/memmachine/common/embedder/embedder.py
src/memmachine/common/embedder/openai_embedder.py
src/memmachine/common/language_model/language_model.py
src/memmachine/common/language_model/openai_language_model.py
src/memmachine/episodic_memory/declarative_memory/declarative_memory.py
src/memmachine/episodic_memory/short_term_memory/session_memory.py
src/memmachine/profile_memory/profile_memory.py

IOError is an OSError and should not be used to represent external API errors.
ValueError is better-suited for the immediate arguments to the methods.
There are misspellings in docstring.
Simplify exception handling logic.
Improve security.
Rework exception handling for embedder and language models.
Now raise:
ExternalServiceAPIError: custom generic type to represent API errors from external services
ValueError: invalid arguments for method
RuntimeError: catch-all for other caught errors
Some exception handling blocks have been combined.
Attempt number and sleep_seconds have been made more human-readable.
More logging has been added. Logs are augmented with call uuid so that asynchronous logs can be parsed/read.
Instead of raising exceptions from OpenAI exceptions, which can introduce …

Rework model exception handling
